/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NgabarinUTS;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author elgisundari
 */
public class divisi extends javax.swing.JFrame {
    SQLConnection connect;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(divisi.class.getName());

    /**
     * Creates new form divisi
     */
    public divisi() {
        connect = new SQLConnection();
        initComponents();        
        setSize(1440, 1024); 
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(245, 243, 240));
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/logo_sidebar.png"));
        Image scaledImage = icon.getImage().getScaledInstance(275, 134, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(scaledImage));
        
        icon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/Maman Man.png"));
        scaledImage = icon.getImage().getScaledInstance(254, 90, Image.SCALE_SMOOTH);
        maman.setIcon(new ImageIcon(scaledImage));
        
        // resize icon tombol Dashboard
        ImageIcon dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/dashboard bar.png"));
        Image dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        dashboard.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/event bar.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        event.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/divisi bar.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        divisi.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/manajemen bar.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        tugas.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/progress bar.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        progress.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/laporan bar.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        laporan.setIcon(new ImageIcon(dashboardImg));
        
        // resize icon tombol Dashboard
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/pengaturan.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        pengaturan.setIcon(new ImageIcon(dashboardImg));
        
        dashboardIcon = new ImageIcon(getClass().getResource("/NgabarinUTS/assets/Frame 439.png"));
        dashboardImg = dashboardIcon.getImage().getScaledInstance(320, 50, Image.SCALE_SMOOTH);
        keluar.setIcon(new ImageIcon(dashboardImg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        divisi = new javax.swing.JButton();
        event = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        tugas = new javax.swing.JButton();
        progress = new javax.swing.JButton();
        pengaturan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        maman = new javax.swing.JLabel();
        tambah1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setPreferredSize(new java.awt.Dimension(275, 134));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Frame 439.png"))); // NOI18N
        keluar.setContentAreaFilled(false);
        keluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        keluar.setPreferredSize(new java.awt.Dimension(250, 50));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 880, -1, -1));

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/laporan bar.png"))); // NOI18N
        laporan.setContentAreaFilled(false);
        laporan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        laporan.setMargin(new java.awt.Insets(0, 10, 0, 0));
        laporan.setPreferredSize(new java.awt.Dimension(320, 50));
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        divisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/divisi bar.png"))); // NOI18N
        divisi.setContentAreaFilled(false);
        divisi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divisi.setMargin(new java.awt.Insets(0, 10, 0, 0));
        divisi.setPreferredSize(new java.awt.Dimension(320, 50));
        divisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisiActionPerformed(evt);
            }
        });
        getContentPane().add(divisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/event bar.png"))); // NOI18N
        event.setContentAreaFilled(false);
        event.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        event.setMargin(new java.awt.Insets(0, 10, 0, 0));
        event.setPreferredSize(new java.awt.Dimension(320, 50));
        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });
        getContentPane().add(event, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/dashboard bar.png"))); // NOI18N
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.setFocusPainted(false);
        dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dashboard.setMargin(new java.awt.Insets(0, 10, 0, 0));
        dashboard.setPreferredSize(new java.awt.Dimension(320, 50));
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        tugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/manajemen bar.png"))); // NOI18N
        tugas.setContentAreaFilled(false);
        tugas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tugas.setMargin(new java.awt.Insets(0, 10, 0, 0));
        tugas.setPreferredSize(new java.awt.Dimension(320, 50));
        tugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugasActionPerformed(evt);
            }
        });
        getContentPane().add(tugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        progress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/progress bar.png"))); // NOI18N
        progress.setContentAreaFilled(false);
        progress.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        progress.setMargin(new java.awt.Insets(0, 10, 0, 0));
        progress.setPreferredSize(new java.awt.Dimension(320, 50));
        progress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressActionPerformed(evt);
            }
        });
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Pengaturan.png"))); // NOI18N
        pengaturan.setContentAreaFilled(false);
        pengaturan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pengaturan.setMargin(new java.awt.Insets(0, 10, 0, 0));
        pengaturan.setPreferredSize(new java.awt.Dimension(320, 50));
        pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/tambah.png"))); // NOI18N
        tambah.setToolTipText("");
        tambah.setContentAreaFilled(false);
        tambah.setPreferredSize(new java.awt.Dimension(183, 53));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Group 7.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(913, 66));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(916, 583));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/nama divisi.png"))); // NOI18N
        jLabel3.setText("Nama");
        jLabel3.setPreferredSize(new java.awt.Dimension(714, 53));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));
        jLabel3.getAccessibleContext().setAccessibleName("");

        maman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Maman Man.png"))); // NOI18N
        maman.setPreferredSize(new java.awt.Dimension(254, 90));
        getContentPane().add(maman, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        tambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/tambah.png"))); // NOI18N
        tambah1.setToolTipText("");
        tambah1.setContentAreaFilled(false);
        tambah1.setPreferredSize(new java.awt.Dimension(183, 53));
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Tambah Divisi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("Divisi & Anggota");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Rectangle 17.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(920, 155));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/Rectangle 20.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(999, 932));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NgabarinUTS/assets/gradiens sidebar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(320, 1024));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventActionPerformed

    private void divisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divisiActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanActionPerformed

    private void tugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugasActionPerformed

    private void progressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressActionPerformed

    private void pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengaturanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi Logout", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            new Login().setVisible(true);  // ganti ke frame login kamu
            dispose();  // tutup frame sekarang
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new divisi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboard;
    private javax.swing.JButton divisi;
    private javax.swing.JButton event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel maman;
    private javax.swing.JButton pengaturan;
    private javax.swing.JButton progress;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tambah1;
    private javax.swing.JButton tugas;
    // End of variables declaration//GEN-END:variables
}
