package NgabarinUTS;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Svin
 */
public class Login extends javax.swing.JFrame {
    SQLConnection connect;

    /**
     * Creates new form Login
     */
    public Login() {
        connect = new SQLConnection();
        initComponents();        
        setSize(830, 500); 
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        
        // formating bg               
        bg_left.setIcon(new ImageIcon(
            new ImageIcon(getClass().getResource("assets/Rectangle 1.png"))
            .getImage()
            .getScaledInstance(bg_left.getWidth(), bg_left.getHeight(), Image.SCALE_SMOOTH)
        ));
        
        titleImg.setIcon(new ImageIcon(
                new ImageIcon(getClass().getResource("assets/Frame 5.png"))
                .getImage()
                .getScaledInstance(titleImg.getWidth(), titleImg.getHeight(), Image.SCALE_SMOOTH)
        ));
        
        welcome.setIcon(new ImageIcon(
                new ImageIcon(getClass().getResource("assets/loginTop.png"))
                .getImage()
                .getScaledInstance(welcome.getWidth(), welcome.getHeight(), Image.SCALE_SMOOTH)
        ));
        
        submitBtn.setIcon(new ImageIcon(
               new ImageIcon(getClass().getResource("assets/Frame 424.png"))
               .getImage()
               .getScaledInstance(submitBtn.getWidth(), submitBtn.getHeight(), Image.SCALE_SMOOTH) 
        ));
        
        
        // element styling
        username.setBorder(new RoundedBorder(Color.GRAY, 10, 1));
        password.setBorder(new RoundedBorder(Color.GRAY, 10, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleImg = new javax.swing.JLabel();
        bg_left = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        submitBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleImg.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(titleImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 230, 230));

        bg_left.setBackground(new java.awt.Color(0, 204, 204));
        bg_left.setForeground(new java.awt.Color(255, 255, 255));
        bg_left.setOpaque(true);
        getContentPane().add(bg_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 500));

        welcome.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 340, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Username atau Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 320, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 320, 40));

        submitBtn.setBackground(new java.awt.Color(0, 255, 255));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 270, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Daftar Sekarang");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Lupa Password?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Belum punya akun? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        if (inputValidation()) {
            if (checkAccount()) {
                JOptionPane.showMessageDialog(rootPane, "Berhasil");
            } else {
                JOptionPane.showMessageDialog(rootPane, "GA ADA BROK");
            }
        }
    }//GEN-LAST:event_submitBtnMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Signup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    private Boolean inputValidation(){
        if (username.getText().equals("") || password.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Isi Semua Input", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } return true;
    }
    
    private Boolean checkAccount(){
        String query = "SELECT * FROM user_table where username = '"+ username.getText() +"' and password = '"+ password.getText() +"'";
        try {
            Statement st = connect.con.createStatement();
            ResultSet res = st.executeQuery(query);
            Boolean found = res.next();
            
            connect.con.close();
            return found;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Err: " + e.getMessage());
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_left;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField password;
    private javax.swing.JLabel submitBtn;
    private javax.swing.JLabel titleImg;
    private javax.swing.JTextField username;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
